export const mergeQueueMigrationStatements = [
  `pragma foreign_keys = off`,
  `create table nodes_new (
    id text primary key,
    title text not null,
    kind text not null check (kind in ('feature','fix','refactor','test','docs','infra','audit-fix')),
    milestone text,
    status text not null check (status in ('draft','ready','claimed','working','review','fixing','ci','mergeable','queued','done','regressed','blocked','cancelled')),
    priority text not null check (priority in ('P0','P1','P2','P3')),
    estimate_points integer not null default 1,
    risk text not null check (risk in ('low','medium','high')),
    owner text,
    branch text,
    spec text not null,
    acceptance text not null,
    validation text,
    context text,
    created_at text not null,
    updated_at text not null,
    claimed_at text,
    done_at text,
    group_name text,
    projects_json text not null default '[]',
    verification_json text not null default '[]',
    audit_focus_json text not null default '[]',
    status_reason text,
    check_command text,
    ci_command text,
    blocked_by text check (blocked_by in ('manual','external','policy','environment','credential','provider','data','external-dependency')),
    blocked_reason text,
    blocked_owner text,
    pr_number integer,
    pr_url text,
    merge_queue_entry_id text,
    merge_queue_enqueued_at text,
    merge_group_sha text,
    merge_queue_ejected_at text,
    merge_queue_ejection_reason text
  )`,
  `insert into nodes_new (
    id, title, kind, milestone, status, priority, estimate_points, risk, owner, branch,
    spec, acceptance, validation, context, created_at, updated_at, claimed_at, done_at,
    group_name, projects_json, verification_json, audit_focus_json, status_reason, check_command, ci_command,
    blocked_by, blocked_reason, blocked_owner, pr_number, pr_url
  )
    select id, title, kind, milestone, status, priority, estimate_points, risk, owner, branch,
      spec, acceptance, validation, context, created_at, updated_at, claimed_at, done_at,
      group_name, projects_json, verification_json, audit_focus_json, status_reason, check_command, ci_command,
      blocked_by, blocked_reason, blocked_owner, pr_number, pr_url
    from nodes`,
  `drop table nodes`,
  `alter table nodes_new rename to nodes`,
  `create index if not exists idx_nodes_status on nodes(status)`,
  `create index if not exists idx_nodes_group on nodes(group_name)`,
  `create index if not exists idx_nodes_pr_number on nodes(pr_number)`,
  `create index if not exists idx_nodes_merge_queue_entry on nodes(merge_queue_entry_id)`,
  `pragma foreign_keys = on`,
] as const;
